export const Animes = [
  {
    id: 10,
    title: "Great Teacher Onizuka",
    category: ["Comédia", "Vida escolar", "Amadurecimento"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/220/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/220/large.jpg",
    original: "Great Teacher Onizuka",
    status: "Concluído",
    launch_date: "1999",
    studio: "Estúdio Pierrot",
    synopsis:
      "Onizuka é um líder de gangue de motoqueiros reformado que está de olho em uma nova e honrosa ambição: se tornar o maior professor do mundo... com o objetivo de conhecer garotas sexy do ensino médio. Ok, então ele é principalmente reformado. No entanto, administradores rigorosos e uma classe de delinquentes implacáveis ​​estão entre Onizuka e seu objetivo e eles usarão qualquer meio, por ilegal ou baixo, para afastar o novo professor. Perfeito, pois os métodos de Onizuka não serão encontrados em nenhum manual de ensino; ele se importa com a diferença entre atividades legais e ilegais tanto quanto se importa com a diferença de idade entre ele e uma garota do ensino médio. Então prepare-se para matemática que não faz sentido, linguagem que você levaria um tapa por usar e biologia que faria um homem adulto corar... a menos, é claro, que você seja o Grande Professor Onizuka.",
  },
  {
    id: 11,
    title: "Ore Monogatari!!",
    category: ["Comédia", "Shoujo", "Romance"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/10016/original.png",
    image_url: "https://media.kitsu.io/anime/poster_images/10016/large.jpg",
    original: "Ore Monogatari!!",
    status: "Concluído",
    launch_date: "2015",
    studio: "Hospício",
    synopsis:
      "Com sua construção muscular e estatura alta, Takeo Gouda não é exatamente um calouro médio do ensino médio. No entanto, por trás de sua aparência intimidadora esconde um coração de ouro, e ele é considerado um herói pelos meninos por sua coragem e cavalheirismo. Infelizmente, essas características não ajudam muito em sua vida amorosa. Como se sua aparência não fosse suficiente para assustar o sexo oposto, o melhor amigo legal e bonito de Takeo e companheiro constante Makoto Sunakawa facilmente rouba os corações das alunas - incluindo todas as garotas que Takeo já gostou. Quando Takeo corajosamente salva a fofa e angelical Rinko Yamato de ser molestada, ele se apaixona por ela instantaneamente, mas suspeita que ela possa estar interessada em Sunakawa. Com seu próprio amor por Yamato continuando a florescer, Takeo desinteressadamente decide agir como seu cupido, mesmo quando ele anseia por sua própria história de amor.",
  },
  {
    id: 12,
    title: "Princess Mononoke",
    category: ["Ação", "Aventura", "Passado", "Samurai"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/142/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/142/large.jpg",
    original: "Mononoke Hime",
    status: "Concluído",
    launch_date: "1997",
    studio: "Studio Ghibli",
    synopsis:
      "Quando uma aldeia Emishi é atacada por um feroz javali demônio, o jovem príncipe Ashitaka coloca sua vida em risco para defender sua tribo. Com seu último suspiro, a fera amaldiçoa o braço do príncipe, concedendo-lhe poderes demoníacos enquanto gradualmente drena sua vida. Instruído pelos anciões da aldeia a viajar para o oeste em busca de uma cura, Ashitaka chega a Tatara, a Cidade de Ferro, onde se vê envolvido em um conflito feroz: Lady Eboshi de Tatara, promovendo o desmatamento constante, se opõe à princesa San e aos espíritos sagrados do floresta, que estão furiosos com a destruição trazida pelos humanos. À medida que as forças opostas da natureza e da humanidade começam a se chocar em uma luta desesperada pela sobrevivência, Ashitaka tenta buscar a harmonia entre os dois, enquanto luta contra o demônio latente dentro dele. Princesa Mononoke é um conto que descreve a conexão entre tecnologia e natureza, enquanto mostra o caminho para a harmonia que pode ser alcançada pela aceitação mútua.",
  },
  {
    id: 13,
    title: "Dragon Ball",
    category: ["Ação", "Aventura", "Shounen", "Comédia"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/199/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/199/large.jpg",
    original: "Dragon Ball",
    status: "Concluído",
    launch_date: "1986",
    studio: " Toei Animation",
    synopsis:
      "Gokuu Son é um garoto que vive sozinho na floresta - isto é, até que uma garota chamada Bulma o encontra em sua busca por um conjunto de objetos mágicos chamados 'Dragon Balls'. Como dizem que os artefatos concedem um desejo a quem coletar todos os sete, Bulma espera reuni-los e desejar um namorado perfeito. Gokuu está de posse de uma esfera do dragão, mas infelizmente para Bulma, ele se recusa a se separar dela, então ela faz um acordo com ele: ele pode acompanhá-la em sua jornada se ele a deixar emprestar o poder da esfera do dragão. Com isso, os dois partiram na jornada de uma vida. Eles não vão na jornada sozinhos. No caminho, eles encontram o velho Muten-Roshi e aspirante a discípulo Kuririn, com quem Gokuu treina para se tornar um artista marcial mais forte para o próximo Torneio Mundial de Artes Marciais. No entanto' nem tudo é diversão e jogos; a capacidade de realizar qualquer desejo é poderosa, e há outras que fariam muito pior do que apenas desejar um namorado. Para impedir aqueles que tentam abusar do poder lendário, eles treinam para se tornarem lutadores mais fortes, usando sua força recém-descoberta para ajudar as pessoas ao seu redor ao longo do caminho.",
  },
];
