export const categories = [
  "Acao",
  "Aventura",
  "Faroeste",
  "Romance",
  "Drama",
  "Comedia",
  "Parodia ou Aniparo",
  "Sci-fi",
  "Horror",
  "Guerra",
  "Policial-Investigacao",
  "Jogos-Esportes",
  "Artes Marciais",
  "Isekai",
  "Shounen",
  "Shojo",
  "Josei",
  "Seinen",
  "Kodomo",
  "Bishonen",
  "Bishoujo",
  "Harem",
  "Fantasia",
  "Pos-Apocaliptico",
  "Space-opera",
  "Historico",
  "Supernatural",
  "Slice-of-life",
  "Vida-escolar",
  "Mecha",
  "Ecchi",
  "Kodomomuke",
];

export const Animes = [
  {
    id: 10,
    title: "Great Teacher Onizuka",
    category: ["Comédia", "Vida escolar", "Amadurecimento"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/220/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/220/large.jpg",
    original: "Great Teacher Onizuka",
    status: "Concluído",
    launch_date: "1999",
    studio: "Estúdio Pierrot",
    synopsis:
      "Onizuka é um líder de gangue de motoqueiros reformado que está de olho em uma nova e honrosa ambição: se tornar o maior professor do mundo... com o objetivo de conhecer garotas sexy do ensino médio. Ok, então ele é principalmente reformado. No entanto, administradores rigorosos e uma classe de delinquentes implacáveis ​​estão entre Onizuka e seu objetivo e eles usarão qualquer meio, por ilegal ou baixo, para afastar o novo professor. Perfeito, pois os métodos de Onizuka não serão encontrados em nenhum manual de ensino; ele se importa com a diferença entre atividades legais e ilegais tanto quanto se importa com a diferença de idade entre ele e uma garota do ensino médio. Então prepare-se para matemática que não faz sentido, linguagem que você levaria um tapa por usar e biologia que faria um homem adulto corar... a menos, é claro, que você seja o Grande Professor Onizuka.",
  },
  {
    id: 11,
    title: "Ore Monogatari!!",
    category: ["Comédia", "Shoujo", "Romance"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/10016/original.png",
    image_url: "https://media.kitsu.io/anime/poster_images/10016/large.jpg",
    original: "Ore Monogatari!!",
    status: "Concluído",
    launch_date: "2015",
    studio: "Hospício",
    synopsis:
      "Com sua construção muscular e estatura alta, Takeo Gouda não é exatamente um calouro médio do ensino médio. No entanto, por trás de sua aparência intimidadora esconde um coração de ouro, e ele é considerado um herói pelos meninos por sua coragem e cavalheirismo. Infelizmente, essas características não ajudam muito em sua vida amorosa. Como se sua aparência não fosse suficiente para assustar o sexo oposto, o melhor amigo legal e bonito de Takeo e companheiro constante Makoto Sunakawa facilmente rouba os corações das alunas - incluindo todas as garotas que Takeo já gostou. Quando Takeo corajosamente salva a fofa e angelical Rinko Yamato de ser molestada, ele se apaixona por ela instantaneamente, mas suspeita que ela possa estar interessada em Sunakawa. Com seu próprio amor por Yamato continuando a florescer, Takeo desinteressadamente decide agir como seu cupido, mesmo quando ele anseia por sua própria história de amor.",
  },
  {
    id: 12,
    title: "Princess Mononoke",
    category: ["Ação", "Aventura", "Passado", "Samurai"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/142/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/142/large.jpg",
    original: "Mononoke Hime",
    status: "Concluído",
    launch_date: "1997",
    studio: "Studio Ghibli",
    synopsis:
      "Quando uma aldeia Emishi é atacada por um feroz javali demônio, o jovem príncipe Ashitaka coloca sua vida em risco para defender sua tribo. Com seu último suspiro, a fera amaldiçoa o braço do príncipe, concedendo-lhe poderes demoníacos enquanto gradualmente drena sua vida. Instruído pelos anciões da aldeia a viajar para o oeste em busca de uma cura, Ashitaka chega a Tatara, a Cidade de Ferro, onde se vê envolvido em um conflito feroz: Lady Eboshi de Tatara, promovendo o desmatamento constante, se opõe à princesa San e aos espíritos sagrados do floresta, que estão furiosos com a destruição trazida pelos humanos. À medida que as forças opostas da natureza e da humanidade começam a se chocar em uma luta desesperada pela sobrevivência, Ashitaka tenta buscar a harmonia entre os dois, enquanto luta contra o demônio latente dentro dele. Princesa Mononoke é um conto que descreve a conexão entre tecnologia e natureza, enquanto mostra o caminho para a harmonia que pode ser alcançada pela aceitação mútua.",
  },
  {
    id: 13,
    title: "Dragon Ball",
    category: ["Ação", "Aventura", "Shounen", "Comédia"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/199/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/199/large.jpg",
    original: "Dragon Ball",
    status: "Concluído",
    launch_date: "1986",
    studio: " Toei Animation",
    synopsis:
      "Gokuu Son é um garoto que vive sozinho na floresta - isto é, até que uma garota chamada Bulma o encontra em sua busca por um conjunto de objetos mágicos chamados 'Dragon Balls'. Como dizem que os artefatos concedem um desejo a quem coletar todos os sete, Bulma espera reuni-los e desejar um namorado perfeito. Gokuu está de posse de uma esfera do dragão, mas infelizmente para Bulma, ele se recusa a se separar dela, então ela faz um acordo com ele: ele pode acompanhá-la em sua jornada se ele a deixar emprestar o poder da esfera do dragão. Com isso, os dois partiram na jornada de uma vida. Eles não vão na jornada sozinhos. No caminho, eles encontram o velho Muten-Roshi e aspirante a discípulo Kuririn, com quem Gokuu treina para se tornar um artista marcial mais forte para o próximo Torneio Mundial de Artes Marciais. No entanto' nem tudo é diversão e jogos; a capacidade de realizar qualquer desejo é poderosa, e há outras que fariam muito pior do que apenas desejar um namorado. Para impedir aqueles que tentam abusar do poder lendário, eles treinam para se tornarem lutadores mais fortes, usando sua força recém-descoberta para ajudar as pessoas ao seu redor ao longo do caminho.",
  },
  {
    id: 2,
    title: "One Piece",
    category: ["Ação", "Crime", "Comédia", "Pirata"],
    rate: [],
    banner_url:
      "https://media.kitsu.io/anime/12/cover_image/21ecb556255bd46b95aea4779d19789f.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/12/large.jpg",
    original: "One Piece",
    status: "Em exibição",
    launch_date: "1999",
    studio: "Toei Animation",
    synopsis:
      "Gol D. Roger era conhecido como o 'Rei dos Piratas', o ser mais forte e mais infame que navegou na Grand Line. A captura e morte de Roger pelo Governo Mundial trouxe uma mudança em todo o mundo. Suas últimas palavras antes de sua morte revelaram a existência do maior tesouro do mundo, One Piece. Foi essa revelação que trouxe a Grande Era dos Piratas, homens que sonhavam em encontrar One Piece - que promete uma quantidade ilimitada de riqueza e fama - e possivelmente o auge da glória e o título de Rei dos Piratas. Entra Monkey D. Luffy, um garoto de 17 anos que desafia sua definição padrão de pirata. Em vez da persona popular de um pirata perverso, endurecido e desdentado saqueando aldeias por diversão, a razão de Luffy ser um pirata é de pura admiração: o pensamento de uma aventura emocionante que o leva a pessoas intrigantes e, finalmente, ao tesouro prometido. Seguindo os passos de seu herói de infância, Luffy e sua tripulação viajam pela Grand Line, vivenciando aventuras loucas, desvendando mistérios sombrios e lutando contra inimigos fortes, tudo para alcançar a mais cobiçada de todas as fortunas – One Piece.",
  },
  {
    id: 3,
    title: "Demon Slayer",
    category: ["Ação", "Aventura", "Demônio", "Fantasia"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/41370/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/41370/large.jpg",
    original: "Kimetsu no Yaiba",
    status: "Concluído",
    launch_date: "2019",
    studio: "ufotable",
    synopsis:
      "É o Período Taisho no Japão. Tanjiro, um menino de bom coração que vende carvão para viver, encontra sua família massacrada por um demônio. Para piorar a situação, sua irmã mais nova Nezuko, a única sobrevivente, foi transformada em um demônio. Embora devastado por essa realidade sombria, Tanjiro resolve se tornar um “matador de demônios” para que ele possa transformar sua irmã em humana e matar o demônio que massacrou sua família.",
  },
  {
    id: 4,
    title: "Boku no Hero Academia",
    category: ["Ação", "Comédia", "Shounen", "Super-hérois "],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/11469/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/11469/large.jpg",
    original: "Boku no Hero Academia",
    status: "Concluído",
    launch_date: "2016",
    studio: "OSSOS, Ossos",
    synopsis:
      "Como seria o mundo se 80% da população manifestasse superpoderes extraordinários chamados “Peculiaridades” aos quatro anos? Heróis e vilões estariam lutando em todos os lugares! Tornar-se um herói significaria aprender a usar seu poder, mas onde você iria estudar? Programa Hero da UA High, é claro! Mas o que você faria se fosse um dos 20% que nasceram Quirkless? O estudante do ensino médio Izuku Midoriya quer ser um herói mais do que tudo, mas ele não tem um pingo de poder nele. Sem chance de entrar na prestigiosa UA High School para heróis iniciantes, sua vida está parecendo cada vez mais um beco sem saída. Então, um encontro com All Might, o maior herói de todos, dá a ele a chance de mudar seu destino… (Fonte: Viz Media)",
  },
];

export const Animes2 = [
  {
    id: 3,
    title: "Demon Slayer",
    category: ["Ação", "Aventura", "Demônio", "Fantasia"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/41370/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/41370/large.jpg",
    original: "Kimetsu no Yaiba",
    status: "Concluído",
    launch_date: "2019",
    studio: "ufotable",
    synopsis:
      "É o Período Taisho no Japão. Tanjiro, um menino de bom coração que vende carvão para viver, encontra sua família massacrada por um demônio. Para piorar a situação, sua irmã mais nova Nezuko, a única sobrevivente, foi transformada em um demônio. Embora devastado por essa realidade sombria, Tanjiro resolve se tornar um “matador de demônios” para que ele possa transformar sua irmã em humana e matar o demônio que massacrou sua família.",
  },
  {
    id: 4,
    title: "Boku no Hero Academia",
    category: ["Ação", "Comédia", "Shounen", "Super-hérois "],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/11469/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/11469/large.jpg",
    original: "Boku no Hero Academia",
    status: "Concluído",
    launch_date: "2016",
    studio: "OSSOS, Ossos",
    synopsis:
      "Como seria o mundo se 80% da população manifestasse superpoderes extraordinários chamados “Peculiaridades” aos quatro anos? Heróis e vilões estariam lutando em todos os lugares! Tornar-se um herói significaria aprender a usar seu poder, mas onde você iria estudar? Programa Hero da UA High, é claro! Mas o que você faria se fosse um dos 20% que nasceram Quirkless? O estudante do ensino médio Izuku Midoriya quer ser um herói mais do que tudo, mas ele não tem um pingo de poder nele. Sem chance de entrar na prestigiosa UA High School para heróis iniciantes, sua vida está parecendo cada vez mais um beco sem saída. Então, um encontro com All Might, o maior herói de todos, dá a ele a chance de mudar seu destino… (Fonte: Viz Media)",
  },
  {
    id: 5,
    title: "Noragami",
    category: ["Ação", "Aventura", "Comédia", "Super Poderes"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/7881/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/7881/large.jpg",
    original: "Noragami",
    status: "Concluído",
    launch_date: "2014",
    studio: "Bones",
    synopsis:
      "Em momentos de necessidade, se você procurar no lugar certo, poderá ver um número de telefone estranho rabiscado em vermelho. Se você ligar para este número, você ouvirá um jovem se apresentar como o Deus Yato. Yato é uma divindade menor e um autoproclamado 'Deus da Entrega', que sonha em ter milhões de adoradores. Sem um único santuário dedicado ao seu nome, no entanto, seus objetivos estão longe de serem realizados. Ele passa seus dias fazendo biscates por cinco ienes cada, até que seu parceiro de armas fica farto de seu mestre inútil e o abandona. Assim como as coisas parecem sombrias para o deus, sua fortuna muda quando uma garota do ensino médio, Hiyori Iki, supostamente salva Yato de um acidente de carro, levando o golpe por ele. Notavelmente, ela sobrevive, mas o evento fez com que sua alma se soltasse e, portanto, pudesse deixar seu corpo. Hiyori exige que Yato a devolva ao normal, mas ao saber que ele precisa de um novo parceiro para fazê-lo, relutantemente concorda em ajudá-lo a encontrar um. E com a ajuda de Hiyori, a sorte de Yato pode finalmente estar mudando.",
  },
  {
    id: 6,
    title: "Avatar: The Last Airbender",
    category: ["Ação", "Comédia", "Aventura", "Artes marciais"],
    rate: [],
    banner_url: "image",
    image_url: "https://media.kitsu.io/manga/poster_images/39307/large.jpg",
    original: "Avatar: The Last Airbender",
    status: "Concluído",
    launch_date: "2006",
    studio: "Nickelodeon Animation Studio",
    synopsis:
      "A mania dos desenhos animados de sucesso da Nickelodeon vai para TOKYOPOP, enquanto você revive cada episódio emocionante... agora na forma de cine-mangá fácil de seguir! Em uma busca atemporal que reúne todos os elementos (trocadilho!) da história e cultura asiáticas, Avatar: the Last Airbender tem a mistura perfeita de ação, comédia e aventura! E onde as artes marciais se traduzem em 'levitar-pedras-e-jogá-las-na-cara-do-seu-inimigo', você só quer pular direto e se juntar à escola de karatê local! Não há dúvida de que Avatar: o Último Mestre do Ar ficou rico com fãs em toda a linha, e este editor é apenas um deles! ATLA sacia minha sede por culturas asiáticas geralmente não vistas no mundo da animação, enquanto me atrai ainda mais com magia e ação! E com uma nova mistura de personagens, de um irmão mais velho sarcástico a uma legião de garotas chutando bundas, Continuo voltando! Com apenas duas temporadas concluídas, e quatro completas a serem esperadas, ATLA certamente terá muito mais a oferecer aos seus fãs leais.",
  },
  {
    id: 7,
    title: "Hunter x Hunter",
    category: ["Ação", "Aventura", "Drama", "Shounen"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/6448/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/6448/large.jpg",
    original: "Hunter x Hunter",
    status: "Concluído",
    launch_date: "2011",
    studio: "MADHOUSE, Madhouse",
    synopsis:
      "Hunter x Hunter se passa em um mundo onde os caçadores existem para realizar todo tipo de tarefas perigosas, como capturar criminosos e corajosamente procurar tesouros perdidos em territórios desconhecidos. Gon Freecss, de doze anos, está determinado a se tornar o melhor caçador possível na esperança de encontrar seu pai, que era um caçador e abandonou seu filho há muito tempo. No entanto, Gon logo percebe que o caminho para alcançar seus objetivos é muito mais desafiador do que ele jamais poderia imaginar. Ao longo do caminho para se tornar um caçador oficial, Gon faz amizade com o animado médico em treinamento Leorio, o vingativo Kurapika e o rebelde ex-assassino Killua. Para atingir seus próprios objetivos e desejos, os quatro fazem juntos o Exame Hunter, notório por sua baixa taxa de sucesso e alta probabilidade de morte. Ao longo de sua jornada, Gon e seus amigos embarcam em uma aventura que os coloca em muitas dificuldades e lutas. Eles conhecerão uma infinidade de monstros, criaturas e personagens - enquanto aprendem o que realmente significa ser um caçador.",
  },
];

export const Animes3 = [
  {
    id: 15,
    title: "Kuroko no Basket",
    category: ["Comédia", "Esportes", "Amizade", "Shounen"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/6595/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/6595/large.jpg",
    original: "Kuroko no Basket",
    status: "Concluído",
    launch_date: "2012",
    studio: "Produção IG",
    synopsis:
      "A equipe de basquete da Teikou Junior High School é coroada campeã três anos consecutivos graças a cinco jogadores excepcionais que, com suas habilidades únicas e de tirar o fôlego, deixam os adversários em desespero e os fãs em admiração. No entanto, depois de se formar, esses companheiros de equipe, conhecidos como 'A Geração dos Milagres', seguem caminhos separados e agora se consideram rivais. Na Seirin High School, dois calouros recém-recrutados provam que não são jogadores de basquete comuns: Taiga Kagami, um jogador promissor que retorna dos EUA, e Tetsuya Kuroko, um estudante aparentemente comum cuja falta de presença permite que ele se mova despercebido. Embora Kuroko não seja atlético nem capaz de marcar pontos, ele foi membro do time de basquete de Teikou, onde jogou como o 'Sexto Homem Fantasma'. que facilmente passou a bola e ajudou seus companheiros de equipe. Kuroko no Basket segue a jornada dos jogadores de Seirin enquanto eles tentam se tornar o melhor time japonês do ensino médio ao vencer o Campeonato Interhigh. Para alcançar seu objetivo, eles precisam cruzar caminhos com várias equipes poderosas, algumas das quais têm um dos cinco jogadores com habilidades divinas, a quem Kuroko e Taiga fazem um pacto para derrotar.",
  },
  {
    id: 16,
    title: "Soul Eater",
    category: ["Ação", "Aventura", "Comédia", "Shounen"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/3128/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/3128/large.jpg",
    original: "Soul Eater",
    status: "Concluído",
    launch_date: "2008",
    studio: "Bones",
    synopsis:
      "Death City é o lar da famosa Shibusen, uma academia técnica liderada pelo próprio Shinigami-Lord Death. Sua missão: levantar 'Death Scythes' para o Shinigami usar contra os muitos males de seu mundo fantástico. Essas foices da morte, no entanto, não são feitas de armas físicas; em vez disso, eles nascem de híbridos humanos que têm a capacidade de transformar seus corpos em Armas Demoníacas, e somente depois de consumirem as almas de 99 seres malignos e a alma de uma bruxa. Soul Eater Evans, um Demon Scythe que só parece se importar com o que é legal, pretende se tornar um Death Scythe com a ajuda de seu portador, ou meister, Maka Albarn. A dupla contrastante trabalha e estuda ao lado do Black☆Star de cabeça quente e sua arma carinhosa Tsubaki, bem como o próprio filho do Shinigami, Death the Kid, um portador duplo obsessivo-compulsivo de pistolas gêmeas Patty e Liz.Soul Eater segue esses estudantes de Shibusen enquanto eles assumem missões para coletar almas e proteger a cidade das ameaças do mundo enquanto trabalham juntos sob o sol risonho para se tornarem mais sãos em mente e corpo , e alma.",
  },
  {
    id: 17,
    title: "Code Geass: Lelouch of the Rebellion R2",
    category: ["Ação", "Drama", "Futuro", "Guerra"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/2634/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/2634/large.jpg",
    original: "Code Geass: Hangyaku no Lelouch R2",
    status: "Concluído",
    launch_date: "2008",
    studio: "Sunrise",
    synopsis:
      "Um ano se passou desde a Rebelião Negra, uma revolta fracassada contra o Sacro Império Britânico liderado pelo vigilante mascarado Zero, que agora está desaparecido. Perdendo sem seu líder revolucionário, o grupo de resistência da Área 11 - os Cavaleiros Negros - encontram-se impotentes demais para combater a brutalidade infligida aos Onze pela Britannia, que aumentou significativamente para esmagar qualquer esperança de uma futura revolta. Lelouch Lamperouge, tendo perdido toda a memória de sua vida dupla, vive pacificamente ao lado de seus amigos como estudante do ensino médio na Ashford Academy. Sua ex-parceira CC, incapaz de aceitar essa reviravolta, se encarrega de lembrá-lo de seu propósito passado, esperando que o mentor Zero ressuscite mais uma vez para terminar o que começou, nesta emocionante conclusão da série.",
  },
  {
    id: 18,
    title: "Yagate Kimi ni Naru",
    category: ["Romance", "Shoujo Ai"],
    rate: [],
    banner_url: "https://media.kitsu.io/anime/cover_images/41240/original.jpg",
    image_url: "https://media.kitsu.io/anime/poster_images/41240/large.jpg",
    original: "Yagate Kimi ni Naru",
    status: "Concluído",
    launch_date: "2018",
    studio: "TROYCA",
    synopsis:
      "Yuu sempre sonhou em receber uma confissão de amor, mas não sente nada quando um garoto lhe dá uma. Confusa, ela começa seu primeiro ano do ensino médio e conhece a bela presidente do conselho estudantil, Nanami, que faz seu coração disparar.",
  },
];
